Controllers/DashController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using RockFS.Data;
using RockFS.Data.Models;
using RockFS.Models.Auth;
using RockFS.Models.Dashboard;
using RockFS.Models.Explorer;
using RockFS.Services.RockFS;
using RockFS.Views.Explorer;

namespace RockFS.Controllers;

[Authorize(Roles = nameof(UserRole.Member))]
public partial class DashController : Controller
{
    private readonly UserManager<RockFsUser> _userManager;
    private readonly RoleService _roleService;
    private readonly RfsService _rfs;

    public DashController(UserManager<RockFsUser> userManager, RoleService roleService, RfsService rfs, ApplicationDbContext context)
    {
        _userManager = userManager;
        _roleService = roleService;
        _rfs = rfs;
        _context = context;
    }

    public IActionResult Mounts()
    {
        return View();
    }
    [Authorize(Roles = nameof(UserRole.Administrator))]
    public IActionResult Users()
    {
        return View();
    }
    [Authorize(Roles = nameof(UserRole.Member))]
    [Route("dash/explore/{mountId:guid}/{*path}")]
    public async Task<IActionResult> Explore(Guid mountId, string? path)
    {
        if (path == null || path == "/") path = "";
        var user = await _userManager.GetUserAsync(User);
        var grant = await _rfs.GetGrant(mountId, new Guid(user.Id));
        string name = "Unauthorized Mount";
        if (grant.MountId != Guid.Empty)
        {
            var mount = await _rfs.GetMountAsync(grant.MountId);
            name = mount.MountFriendlyName;
        }
        var resources = await _rfs.GetResources(grant, path);
        return View(new MountExplorerModel(grant, path, name, resources));
    }
    [Authorize(Roles = nameof(UserRole.Administrator))]
    public async Task<IActionResult> EditMounts(string id)
    {
        var user = await _userManager.FindByIdAsync(id);
        if (user is null) return RedirectToAction("NotFound", "Home");
        return View(new EditMountModel()
        {
            UserId = new Guid(id),
            UserEmail = user.Email,
            Mounts = (from x in await _rfs.GetUserMountsAsync(new Guid(id))
                select (x.MountId.ToString(), x)).ToDictionary(x=>x.Item1, x=>x.x)
        });
    }
    [Authorize(Roles = nameof(UserRole.Administrator))]
    public async Task<IActionResult> EditUser(string id)
    {
        var user = await _userManager.FindByIdAsync(id);
        if (user is null) return RedirectToAction("NotFound", "Home");
        return View(new EditUserModel()
        {
            Role = await _roleService.GetHighestRoleAsync(user),
            IsConfirmed = user.EmailConfirmed,
            UserId = id,
            UserEmail = user.Email,
        });
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using RockFS.Models.Auth
@using RockFS.Services.RockFS
@inject RoleService RoleService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RockFS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/RockFS.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/file-icon-vivid.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rock.</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (await RoleService.IsUserInRole(User, UserRole.Member))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dash" asp-action="Mounts">Mounts</a>
                        </li>
                    }
                    @if (await RoleService.IsUserInRole(User, UserRole.Administrator))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Dash" asp-action="Users">Users</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="rfs-grid h-100">
    <div class="rfs-wrapper">
        <div class="rfs-title">@ViewData["R-Title"]</div>
    </div>
    <div class="p-5 h-100">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap-menu/BootstrapMenu.min.js"></script>
<script src="~/js/build/bundle.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>